## 1. Bibliotecas

In [71]:
import pandas as pd
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity= "all"

## 2. Importar Dados dos Grupos

In [72]:
#importa xlsx
df = pd.read_excel('Resolução case.xlsx')
df.head()

,Data,Grupos de usuários,Parceiro,compradores,comissão,cashback,vendas totais
0,2011-01-01,Grupo 1,Parceiro A,196,10272.872984,3266.588472,93389.7544
1,2011-01-02,Grupo 1,Parceiro A,115,7555.010188,2060.457324,68681.9108
2,2011-01-03,Grupo 1,Parceiro A,82,4839.237062,1358.103066,43993.0642
3,2011-01-04,Grupo 1,Parceiro A,172,10419.398572,2907.173396,94721.8052
4,2011-01-05,Grupo 1,Parceiro A,187,11304.530974,3137.586282,102768.4634

## 2.1 Estratégia
### Rentabilidade
Começando pela análise de rentabilidade de cada grupo, foi utilizado o cálculo de lucro líquido dado pela fórmula *Lucro Líquido = Total de Vendas − (Cashback + Comissão)* e depois divide-se esse lucro pelas vendas totais para obter a porcentagem de cada grupo.

In [73]:
#Criar nova coluna de porcentagem de rentabilidade no dataframe 
df['lucro liquido'] = df['vendas totais'] - (df['cashback'] + df['comissão'])

df['rentabilidade %'] = df['lucro liquido']/df['vendas totais'] *100

df.groupby('Grupos de usuários')['rentabilidade %'].mean().round(2)

Grupos de usuários
Grupo 1    84.72
Grupo 2    83.21
Grupo 3    82.01
Name: rentabilidade %, dtype: float64

Nota-se que a rentabilidade dos grupos estão bem próximas.Deve ser feita uma análise mais profunda das variáveis separadas por grupo para poder escolher a melhor porcentagem para o usuário.

### Número de Compradores e Média da Comissão, Cashback e Vendas Totais
Nesta seção, analisaremos o número de compradores, a média da comissão, do cashback e das vendas de cada grupo. Esses indicadores são essenciais para avaliar o desempenho do programa de cashback e o engajamento dos usuários. O cálculo feito para a média foi a soma de cada variável dividido pelo número de linhas no dataset.

In [74]:
#agrupando os grupos com a soma de compradores
compradores_por_grupo = df.groupby('Grupos de usuários')[['compradores']].sum()
compradores_por_grupo
#média agrupada da comissão, cashback e vendas totais
df.groupby('Grupos de usuários')[['comissão', 'cashback', 'vendas totais']].mean().round(2)

                    compradores
Grupos de usuários
Grupo 1                    9633
Grupo 2                   10814
Grupo 3                   11410

                    comissão  cashback  vendas totais
Grupos de usuários
Grupo 1              6936.31   2537.23       60925.79
Grupo 2              7914.97   4028.93       69816.25
Grupo 3              8346.61   5473.88       73759.29

Observa-se que o Grupo 3 apresenta o maior número de vendedores e as maiores médias para todas as variáveis analisadas. No entanto, ao verificar a rentabilidade, este grupo possui o menor percentual. Isso indica que, apesar dos valores absolutos mais altos, o lucro gerado é o menor em comparação aos Grupos 1 e 2, devido ao alto volume de cashback oferecido.

Por outro lado, o Grupo 1 apresenta resultados inferiores em termos absolutos (como vendas e cashback), mas destaca-se pela maior rentabilidade. Esse desempenho é explicado pelo baixo volume de cashback distribuído, que contribui para um lucro proporcionalmente mais elevado.

Por fim, o Grupo 2 demonstra um equilíbrio ideal entre as variáveis analisadas, sendo o mais vantajoso tanto para a empresa quanto para o usuário. Ele combina um volume de vendas significativo com um percentual de rentabilidade próximo ao do Grupo 1, resultando em uma escolha mais eficiente. A diferença de apenas 1% nas vendas em relação ao Grupo 1 reforça sua atratividade, pois mantém resultados positivos para a empresa sem comprometer a experiência do usuário.

### Vendas por comprador e Cashback por Venda
A análise das vendas por comprador e do cashback por venda foi realizada por meio de um cálculo agregado. Inicialmente, somaram-se as vendas totais, o número de compradores e o cashback de cada grupo de usuários. Em seguida, o total de vendas foi dividido pela quantidade total de compradores em cada grupo, obtendo a média de vendas por comprador. Para calcular o cashback por venda, dividiu-se o valor total de cashback pelas vendas totais.

Essa abordagem estruturada oferece uma visão clara do comportamento médio dos compradores e do cashback dentro de cada grupo. Com essa métrica, é possível identificar quais grupos apresentam maior eficiência em termos de vendas por comprador e de devolução de uma certa porcentagem do produto, além de avaliar o impacto de variáveis, como cashback e comissão, no desempenho médio.

In [75]:
#Criar um mini dataframe auxiliar
soma_vendas_compradores = df.groupby('Grupos de usuários').agg({
    'vendas totais': 'sum',
    'compradores': 'sum'
})

# Calcular as vendas por comprador
soma_vendas_compradores['vendas por comprador'] = soma_vendas_compradores['vendas totais'] / soma_vendas_compradores['compradores']
#formatar resultado para que as casas de milhar e dezena fiquem separadas corretamente
soma_vendas_compradores['vendas totais'] = soma_vendas_compradores['vendas totais'].map('{:,.2f}'.format)
soma_vendas_compradores['compradores'] = soma_vendas_compradores['compradores'].map('{:,}'.format)
soma_vendas_compradores['vendas por comprador'] = soma_vendas_compradores['vendas por comprador'].map('{:,.2f}'.format)

# Exibir os resultados
display(soma_vendas_compradores[['vendas totais', 'compradores', 'vendas por comprador']])

# Agrupar os dados por 'Grupos de usuários' e aplicar o cálculo
media_cashback = df.groupby('Grupos de usuários').apply(
    lambda media_cashback: (media_cashback['vendas totais'] / media_cashback['cashback']).mean().round(2)
)

# Exibir os resultados
print(media_cashback)

                   vendas totais compradores vendas por comprador
Grupos de usuários
Grupo 1             5,605,172.36       9,633               581.87
Grupo 2             6,423,094.67      10,814               593.96
Grupo 3             6,785,854.97      11,410               594.73

Grupos de usuários
Grupo 1    27.06
Grupo 2    18.19
Grupo 3    15.97
dtype: float64

Analisando os dados apresentados, percebe-se que os valores de vendas por comprador são bastante próximos entre os Grupos 2 e 3, mesmo o Grupo 2 tendo 596 compradores a menos. Isso indica que o Grupo 2 consegue ter um ótimo aproveitamento nas vendas, mantendo um desempenho equivalente ao do Grupo 3, mesmo com um número menor de clientes. Além disso, o cashback por venda no Grupo 2 é menor (18,19 contra 27,06 no Grupo 3), o que resulta em um maior lucro para a empresa.

Quando comparamos com o Grupo 1, notamos uma diferença de 12 vendas por comprador (581,87 no Grupo 1 contra 594,73 no Grupo 3). Em relação às vendas totais, o Grupo 1 apresenta mais de 1 milhão a menos em comparação ao Grupo 3 e cerca de 800 mil a menos em relação ao Grupo 2. O cashback por venda do Grupo 1 é o menor entre os três grupos (15,97), mas, por outro lado, o menor volume de vendas totais e o menor número de compradores impactam negativamente seus resultados gerais.

Esses dados demonstram que o Grupo 2 se destaca por sua eficiência em gerar vendas por comprador e por oferecer um custo de cashback mais competitivo em relação ao Grupo 3. Já o Grupo 1 apresenta resultados menos expressivos, tanto no volume total de vendas quanto no desempenho por comprador.

### Porcentagem de Cashback e de Vendas por Grupo
Por fim, analisaremos a porcentagem de vendas e cashback por grupo. Essa métrica é fundamental, pois revela como está sendo distribuído o cashback em relação às vendas realizadas.

O cálculo da porcentagem de cashback é feito dividindo o cashback de cada grupo pelo total de cashback e, em seguida, multiplicando por 100. Da mesma forma, a porcentagem de vendas é obtida dividindo o total de vendas de cada grupo pelo total geral de vendas, também multiplicado por 100.

In [76]:
#somar cashback
total_cashback = df['cashback'].sum()

#Calcular o total de cashback por grupo
cashback_por_grupo = df.groupby('Grupos de usuários')['cashback'].sum()

#Calcular a porcentagem de cashback por grupo em relação ao total de cashback
percentual_cashback_por_grupo = (cashback_por_grupo / total_cashback).round(4) * 100

#Exibir o resultado
display(percentual_cashback_por_grupo)

#somar vendas
total_vendas = df['vendas totais'].sum()

#Calcular o total de vendas por grupo
vendas_por_grupo = df.groupby('Grupos de usuários')['vendas totais'].sum()

#Calcular a porcentagem de cashback por grupo em relação ao total de cashback
percentual_vendas_por_grupo = (vendas_por_grupo / total_vendas).round(4) * 100

#Exibir o resultado
display(percentual_vendas_por_grupo)

Grupos de usuários
Grupo 1    21.07
Grupo 2    33.46
Grupo 3    45.46
Name: cashback, dtype: float64

Grupos de usuários
Grupo 1    29.79
Grupo 2    34.14
Grupo 3    36.07
Name: vendas totais, dtype: float64

Os resultados apresentados mostram que o Grupo 3 possui a maior porcentagem de cashback (45,46%) em relação aos demais grupos, enquanto sua porcentagem de vendas (36,07%) é menor. Essa relação desfavorável reflete uma menor rentabilidade para o grupo, o que compromete sua viabilidade como melhor opção, já que essa alta distribuição de cashback pode torná-lo insustentável.

Já os grupos 1 e 2 demonstram uma situação mais favorável, pois ambos possuem porcentagens de vendas superiores às de cashback. O Grupo 1, com 29,79% de vendas e 21,07% de cashback, apresenta maior rentabilidade devido à menor proporção de cashback em relação às vendas. No entanto, o Grupo 2, com 34,14% de vendas e 33,46% de cashback, mantém um equilíbrio mais próximo entre as métricas, indicando consistência e boa aceitação entre os clientes.

Com base nessas observações, o Grupo 2 se destaca como a melhor opção, apresentando equilíbrio e sustentabilidade, enquanto o Grupo 1 também exibe resultados positivos, embora com menor impacto geral em comparação ao Grupo 2.

## Conclusão
Com base na análise realizada, conclui-se que o Grupo 2 é a melhor escolha considerando os diversos benefícios que ele proporciona e que serão detalhados a seguir. O grupo escolhido apresenta resultados consistentes tanto para os clientes quanto para a empresa, demonstrando um equilíbrio ideal entre vendas e cashback. Essa distribuição mais equilibrada, no ponto de vista de eficiência de custos, resulta em um cenário propício para expansão da base de receita e minimização do custo, portanto maior lucro, através de um nível atrativo de cashback pelo lado da oferta de benefícios.

Além disso, o Grupo 2 oferece uma boa estratégia de cashback que beneficia os clientes sem comprometer negativamente a saúde financeira da empresa. Essa abordagem combina eficiência operacional e atratividade, consolidando o Grupo 2 como a opção mais vantajosa para atender às necessidades dos clientes e, ao mesmo tempo, impulsionar a sustentabilidade e o crescimento da empresa.